site_name: geosmapdemo

site_url: https://zyang91.github.io/geosmapdemo

repo_url: https://github.com/zyang91/geosmapdemo

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
        #   ignore_h1_titles: True
        #   execute: True
        #   execute_ignore: "*.ipynb"
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/zyang91/geosmapdemo/issues
    - API Reference:
          - geosmapdemo module: geosmapdemo.md
    - Python Basic:
         - python/Classes.ipynb
         - python/Conditional_statement.ipynb
         - python/Dictionaries.ipynb
         - python/files_and_exception_handling.ipynb
         - python/function.ipynb
         - python/GEOG510_list.ipynb
         - python/first.ipynb
         - python/user_input_while_loop.ipynb
         - python/working_with_list.ipynb


